# Generated by Django 4.2.16 on 2026-03-17 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ToolLifecycleReport',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('shift', models.CharField(max_length=1)),
                ('cell_no', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=50)),
                ('tool_no', models.CharField(max_length=10)),
                ('machine_number', models.CharField(max_length=50)),
                ('stage_tool', models.CharField(max_length=100)),
                ('sap_code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('make', models.CharField(max_length=100)),
                ('target_life', models.IntegerField()),
                ('actual_life', models.IntegerField()),
                ('reason_for_tool_change', models.CharField(blank=True, max_length=200, null=True)),
                ('waiting', models.IntegerField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('life_achieved_percent', models.FloatField(blank=True, null=True)),
                ('batch_no', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.dynamicfield')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.toollifecyclereport')),
            ],
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cnc_app.dynamicfield')),
            ],
        ),
    ]
