# Generated by Django 4.2.16 on 2026-03-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toollifecyclereport',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
