# Generated by Django 4.2.16 on 2026-03-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_app', '0002_alter_toollifecyclereport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('alphanumeric', 'Alphanumeric'), ('dropdown', 'Dropdown')], max_length=20),
        ),
    ]
