# Generated by Django 4.2.16 on 2026-03-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc_app', '0003_alter_dynamicfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicfield',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
