"""
Django settings for cnc_platform project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from dotenv import load_dotenv
import os

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-61#ihs04w#!nq6=4_e80a@#82($x5gtc^xyepc526oa*q=1ggw')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cnc_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cnc_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cnc_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
 'default': {
  'ENGINE': 'mssql',
  'NAME': os.getenv('DB_NAME', 'cnc_system'),
  'USER': os.getenv('DB_USER', 'sa'),
  'PASSWORD': os.getenv('DB_PASSWORD', 'YourStrong@Pass123'),
  'HOST': os.getenv('DB_HOST', 'localhost'),
  'PORT': os.getenv('DB_PORT', '1433'),
  'OPTIONS': {
      'driver': 'ODBC Driver 17 for SQL Server',
  },
 }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Kolkata"
USE_TZ = True

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {

    "site_title": "CNC Management System",
    "site_header": "CNC Manufacturing Platform",
    "site_brand": "CNC Platform",

    # Sidebar menu order
    "order_with_respect_to": [
        "auth",
        "operations",
        "analytics",
        "cnc_app"
    ],

    # Custom sidebar links
    "custom_links": {

        "operations": [
            {
                "name": "Submit Tool Lifecycle Report",
                "url": "/",
                "icon": "fas fa-file-pen",
                "permissions": ["auth.view_user"]
            },
        ],

        "analytics": [
            {
                "name": "Reports Dashboard",
                "url": "/admin/reports-dashboard/",
                "icon": "fas fa-chart-bar",
                "permissions": ["auth.view_user"]
            }
        ],

    },

    # Icons for built-in apps
    "icons": {
        "cnc_app": "fas fa-industry",
        "auth": "fas fa-users-cog",
        "operations": "fas fa-gears",
        "analytics": "fas fa-chart-line"
    },
    

}